package ve.gob.domain;
// Generated 11/03/2013 09:41:34 AM by Hibernate Tools 3.2.1.GA



/**
 * Auditor generated by hbm2java
 */
public class Auditor  implements java.io.Serializable {


     private long id;
     private Integer version;
     private EstadoAuditor estadoAuditor;
     private String apellido;
     private String cedula;
     private String celular;
     private String comentario;
     private String correo;
     private String login;
     private String nombre;
     private String telefono;

    public Auditor() {
    }

	
    public Auditor(long id) {
        this.id = id;
    }
    public Auditor(long id, EstadoAuditor estadoAuditor, String apellido, String cedula, String celular, String comentario, String correo, String login, String nombre, String telefono) {
       this.id = id;
       this.estadoAuditor = estadoAuditor;
       this.apellido = apellido;
       this.cedula = cedula;
       this.celular = celular;
       this.comentario = comentario;
       this.correo = correo;
       this.login = login;
       this.nombre = nombre;
       this.telefono = telefono;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public EstadoAuditor getEstadoAuditor() {
        return this.estadoAuditor;
    }
    
    public void setEstadoAuditor(EstadoAuditor estadoAuditor) {
        this.estadoAuditor = estadoAuditor;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


